import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';

const url = 'https://randomuser.me/api/?results=10';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [users, setUsers] = useState([]);

  const getUsers = async () => {
    const response = await fetch(url);
    const data = await response.json();
    setUsers(data.results);
  };

  useEffect(() => {
    getUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Hello world</h1>
        <table border={1}>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user, i) => {
              return (
                <tr key={i}>
                  <td>
                    {user.name.first} {user.name.last}
                  </td>
                  <td>{user.email}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
}

// export default function Home(props) {
//   const { users } = props;
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta
//           name="description"
//           content="Generated by create next app"
//         />
//         <meta
//           name="viewport"
//           content="width=device-width, initial-scale=1"
//         />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <h1>Hello world</h1>
//         <table border={1}>
//           <thead>
//             <tr>
//               <th>Name</th>
//               <th>Email</th>
//             </tr>
//           </thead>
//           <tbody>
//             {users &&
//               users.map((user, i) => {
//                 return (
//                   <tr key={i}>
//                     <td>
//                       {user.name.first} {user.name.last}
//                     </td>
//                     <td>{user.email}</td>
//                   </tr>
//                 );
//               })}
//           </tbody>
//         </table>
//       </main>
//     </>
//   );
// }

// export async function getServerSideProps(context) {
//   const response = await fetch(url);
//   const data = await response.json();

//   return {
//     props: { users: data.results },
//   };
// }
